### ISSUE TITLE
Question: "Passed" when I'd expect "Failed"

### ISSUE THREAD

**Issue by ossareh** [hakancelik96/unimport#73]
Hi there, we're just starting to use `unimport` via pre-commit. I'm getting the following output:

```bash
unimport.................................................................Passed
- hook id: unimport
- duration: 1.37s

request at internal/edgeauth/helpers.py:5
```

This seems confusing to me; I'd expect this to return "Failed" or something and exit uncleanly so that pre-commit (which we're using in CI) would fail. 

Here's the pre-commit setup for this check:

```yaml
repos:
  # ..snipped other repos
  - repo: https://github.com/hakancelik96/unimport
    rev: v0.2.7
    hooks:
      - id: unimport
```

I'm probably misunderstanding something. From the docs I see a few options like rewriting, etc, but in our case we just pre-commit to report "Failed" if a change would be made.

If it turns out this is a bug in unimport I'm happy to write the PR for it - I just want to make sure I'm not missing something obvious first :)

**Comment by hakancelik96** [comment]
Hi, thank you but I think this is not a bug, you don't use any arguments in the **.pre-commit-config.yaml**

If there is unused import in your project, you should use the `-r` parameter to auto-remove them, as a result, if it finds unused import, it will fail.

```
-r # auto-remove unused import in your project
```

If you want to include star imports during refactoring please use `--include-star-import`  flag. 
> This feature doesn't work very well in this version, be careful when using

Can you rewrite your **.pre-commit-config.yaml** conf as below and try?

```yaml
  - repo: https://github.com/hakancelik96/unimport
    rev: v0.2.7
    hooks:
      - id: unimport
        args: [-r]
        files: "\\.(py)$"
```
